### ISSUE TITLE
Plans to make this an official libretro core

### ISSUE THREAD

**Issue by paradadf** [libretro/neocd_libretro#1]
Hi Fabrice and happy new year!
 I just found about your core while investigating about neogeo cd and wodered nobody has talked about it on the libretro forum. I haven't tested your core yet, but do you plan to make an official libretro core?

**Comment by barbudreadmon** [comment]
> wodered nobody has talked about it on the libretro forum

We talked about it, but on discord. After reading the documentation i ended up thinking the bios setup is somehow complex (might be easier to just check for neogeo.zip and neocdz.zip from mame/fba in the bios folder), c++11 is also an issue for portability.
On a sidenote, i finally fixed audio track support for neocd in fba today.

**Comment by Darknior** [comment]
Hi, i really love to see you core become official and include in Retropie :)
I wish it will be possible in time ...
You speak about Finalburn, all is working fine now 100% with finalburn ? And with all the same options like in your core with for exemple the skip CD loading ?
Thanks a lot for your work

**Comment by barbudreadmon** [comment]
> You speak about Finalburn, all is working fine now 100% with finalburn ?

It works as expected with the games i tried.

> And with all the same options like in your core with for exemple the skip CD loading ?

This option doesn't exist in fba.

**Comment by Darknior** [comment]
Thanks for your answer, it is really an incredible work :)
I dream to play some of these games from so many years on my PI :)
I will try your core, add it to Retropie too, and also try the last FBA build you update to compare ...
Maybe if you can't make your core official, you can add the skip CD loading option to FBA ?
NeogeoCD loading are really long and boring in real life :( :p

**Comment by barbudreadmon** [comment]
> I dream to play some of these games from so many years on my PI :)

Except if you think enhanced music is worth downgraded graphics, you probably mean "this game", Samurai Shodown RPG is the only exclusive. Afaik, Samurai Shodown RPG in fba needs region set to japan in core option, but it's still saying some kind of warning in japanese, no idea what this is about.

**Comment by Darknior** [comment]
Downgraded graphics ? I don't read informations about that :(
I read enhanced music but so long loading but we can skip them with your core.
Yes i dream to play SS RPG, because we have finally our French translation <3
https://traf.romhack.org/index.php?p=patchs&pid=941

**Comment by barbudreadmon** [comment]
Yeah, a lot of neocd games had frames removed from their animations, or missing sprites.

**Comment by fabrice-martinez** [comment]
Hello everyone! And happy new year too :)
Yes the plan was to have it officially released as a core but I haven't done so yet for various reasons.
First because I've started working on implementing MAME CHD support, but haven't finished it yet.
Second because SNK has started releasing old titles on virtual console, and I didn't want to be seen as cutting the ground under their feet.
Third is I'm having too much fun playing Mirage 2000 missions on DCS (Yes I know^^)
The biggest roadblock though is my job as it requires me to occasionally go into sensitive installations and they do background checks.
I need a blank criminal record for that so I need to tread very, very carefully in everything I do.

By the way, the reason I had created the emulator in the first place is I tend to prefer CD versions of the games. Because of the great soundtracks!

Supporting the BIOS in ZIP form is a good idea: it'll allow people to share the BIOS between emulators. Thanks for that!

**Comment by barbudreadmon** [comment]
@fabrice-martinez We could move this repo to https://github.com/libretro, give you admin rights on the moved repo, and add it to the libretro buildbot. We could also fork your repo instead. Feel free to come on our discord to discuss about it : https://discord.gg/C4amCeV

**Comment by fabrice-martinez** [comment]
I suppose moving the repo would be easiest way, the buildbot will build the new versions as I push them.
(I'm on Discord as "Elta2K6")

**Comment by barbudreadmon** [comment]
Try talking to a user named Autechre on discord, he is in charge of managing repos and rights and already aware of your core.

**Comment by fabrice-martinez** [comment]
Closing this as the core has been moved :)

**Comment by barbudreadmon** [comment]
I don't think it's on the buildbot yet though, is there some blocking stuff to include it on the buildbot ?

**Comment by gouchi** [comment]
- [[Request] to include libneocd_libretro.dll on the buildbot](https://github.com/libretro/libretro-super/issues/1111)
