### ISSUE TITLE
Neo Geo CD Disc Project Issue

### ISSUE THREAD

**Issue by mrogeriodf** [libretro/neocd_libretro#53]
Hello there. 

I can't load games directly from physical CD in Neo Geo CD core. Every time I try to do it,  I get the mesage "failed to load the content"

It's funny because if I use the same emulator in my PC (Neo CD old version) the game runs fine.

I also play them using an emulator from classic Xbox and Dreamcast.

What could be the issue?

Best regards

**Comment by fabrice-martinez** [comment]
This version of NeoCD is made to work with disk images only. Many platforms (like portable consoles) don't have a CD drive.
Another reason to work with images: I wanted to push the emulation to emulate the copy protection of the games too.
I got it working for front and top loader systems but I'm convinced it will never work for CD-Z, so I dropped the idea.

I think it will be possible to run games directly from CD-ROM in the future because the RetroArch team added a CD-ROM interface in the libretro-common repo. I still need to have a look at it.

**Comment by mrogeriodf** [comment]
That's the reason I'm asking for. Nowadays in Retroarch I can run directly from CD-ROM Saturn, PSX, PC Engine, Sega CD and 3DO. It's missing NEO GEO CD for the complete experience. 
I think this is the simpliest way to have a plug and play experience and It's so nostalgic using ours old CDs.

Thank you for your attention.

**Comment by fabrice-martinez** [comment]
I had a look enabling CD-ROM support in RetroArch VFS and it's not promising. (Doesn't work)
Postponed until later.
