### ISSUE TITLE
Update libchdr

### ISSUE THREAD

**Issue by inactive123** [libretro/neocd_libretro#58]
Hi @fabrice-martinez ,

we want to update libchdr across the board to a new version that is no longer dependent on libFLAC.

You can see here a PR that @jdgleaver made sometime ago that back ports the newer libchdr to another libretro core -

https://github.com/libretro/beetle-psx-libretro/pull/782

I've seen that updating libchdr and removing libFLAC is not so trivial since there's parts of neoCD that use libflac directly, so could you make it instead use dr_flac instead? (this is also used internally by libchdr now).

You'll also likely have to pull in libzma , and you'll have to see how that conflicts with the 7zip dependency that is already inside NeoCD.

We'd appreciate it a lot if you, as the author of this core, could do this, since we kinda feel like a fish out of water attempting this ourselves in a foreign codebase.

Thanks!

**Comment by fabrice-martinez** [comment]
Quick update on this:
I've been updating all dependencies to the latest versions.
Worked fine for libogg, libvorbis, zlib but i'm hitting a bit of a roadblock with 7zip and lzma:
The newest libchdr use lzma version 19.0, the obvious thing to do is to upgrade lib7z to the same version (7zip also include lzma)
Doing so breaks https://github.com/libretro/libretro-common/blob/master/file/archive_file_7z.c
The code in this file is tied to the 7zip lib found in https://github.com/libretro/libretro-deps
Some of the structures (notably CSzAr in 7z.h) look quite different so porting to the new version is not trivial.

7zip is only used to be able to look for BIOS files inside 7z archives, I can see 2 solutions:
1/ Remove the ability to look for BIOS files inside 7z archives (not many people use it?) then we only need liblzma
2/ Update lib7z in https://github.com/libretro/libretro-deps and update archive_file_7z.c in https://github.com/libretro/libretro-common

I'm leaning towards 1, it's much simpler.
I just wonder how many bug reports we will receive when 7z archives stop working :s

**Comment by inactive123** [comment]
@jdgleaver 's preference goes out towards 1. Lets' go with that then.

**Comment by fabrice-martinez** [comment]
More updates:
Good news and bad news.

The good news: FLAC audio is reimplemented using dr_flac and working.
I have even fuzzed the old libFLAC implementation vs the new so I'm pretty sure it works.

The bad news: BIOS in .zip files freezes RetroArch. 
This is not because of the new version of zlib, the bug may have been here for a long time. 
The problem seem to be in https://github.com/libretro/libretro-common/blob/master/file/archive_file_zlib.c

In the function zip_file_read you will see the line:
`file_archive_transfer_t state            = {ARCHIVE_TRANSFER_INIT};`
This is partial initialization (the struct has many fields) and the way it's written I suppose ARCHIVE_TRANSFER_INIT goes into the struct member **type**.
In practice this is not what happens and **type** ends up with value zero (ARCHIVE_TRANSFER_NONE).
This trigger an infinite loop in file_archive_parse_file_iterate.

This can be easily fixed like this:
`file_archive_transfer_t state = {0};`
`state.type = ARCHIVE_TRANSFER_INIT;`

But then RetroArch crash just after file_archive_parse_file_iterate with stack heap corruption.
I have not been able so far to find the reason for the heap corruption.

**Comment by inactive123** [comment]
OK, we pushed those changes through. I also let @jdgleaver know about the issue. Let me know what issues still remain after this so we can put it on our radar for maybe early next week.

**Comment by inactive123** [comment]
Hi there @fabrice-martinez , the latest commit unfortunately breaks quite a few platforms-

https://git.libretro.com/libretro/neocd_libretro/-/jobs/281185

Hopefully you can look into it

**Comment by inactive123** [comment]
I fixed it for all platforms now except libnx (Switch) and PS Vita. Hopefully you can fix that.

https://git.libretro.com/libretro/neocd_libretro/-/pipelines/20759

**Comment by inactive123** [comment]
OK, I fixed the 3DS and Vita toolchain issues now too. Hopefully everything is sorted then for now.
