### ISSUE TITLE
Resolution reported incorrectly

### ISSUE THREAD

**Issue by retrorepair** [libretro/neocd_libretro#7]
The core seems to report a resolution of 304x224 to RA instead of the correct 320x224. Not sure why this is but if it's due to overscan options there are none currently exposed to the user.

Here is a screenshot of FFS in FBA in 320x224:
https://ibb.co/c8023HL

And now NeoCD in 304x224:
https://ibb.co/HD9vrCZ

Fantastic work on this core by the way, to my knowledge it's the only Neo Geo CD emulator capable of running all the BIOS and region options for Neo Geo CD 😊👍

**Comment by retrorepair** [comment]
I should probably create a separate issue but there's also missing shadows under the characters on FFS too, not sure if other emulators have this but from memory mame does?

**Comment by fabrice-martinez** [comment]
Hi :)

The 304 thing is intentional. The Neo Geo has a slight overscan when played on a TV which means you never see the 8 pixels at the left and the right of the screen. I remember a couple games having slight glitches on the fix layer, glitches that the game devs never noticed (because of the overscan).
That's why I chose to remove those pixels, that's what you see when playing on a TV.
That said, reconfiguring the renderer to output 320 pixels shouldn't be too hard. 
Maybe it's not worth hiding parts of the screen for rare glitches in a couple games.
I can test that.

As for the shadows, they work fine here:
![image](https://user-images.githubusercontent.com/503579/55281768-b071cc80-5339-11e9-8ecf-c485dd9175f7.png)
Does it happen on a specific level? Or only with certain characters ?
I think it's possible you didn't see the shadows if you were playing in windowed mode, because of vsync issues.
Try fullscreen mode, it may solve the issue.

**Comment by retrorepair** [comment]
Yeah I think missing parts off the screen by default is probably a bad idea, but maybe an option to enable or disable overscan?

Odd about the shadows, I definitely recall not seeing them when I was testing the core vs using my neo geo cd console, I was testing the same level with andy and terry and didn't see shadows. I'll have to check again. Definitely no vsync issues but I see why you'd think that.

I'm surprised this core isn't in buildbot by the way, I only found it by chance. People have been asking about an easier way to load neo geo cd games for ages and this core seems more than mature enough.

**Comment by fabrice-martinez** [comment]
I still need to talk to Autechre about adding the core to buildbot. I'll do that right after I finish a little contribution to https://github.com/radare/radare2

**Comment by fabrice-martinez** [comment]
Implemented in fd77de0d3f557f9d92a78c7bdda44c207f992ab5
Just git pull and recompile.
